const phrases = [
{id: 1,
text: "¿Puede ________ su síntoma?",
answer: "describir"},
{id: 2,
text: "¿Tiene cita ________?",
answer: "hoy"},
{id: 3,
text: "¿Cuál es su ________ completo?",
answer: "nombre"},
{id: 4,
text: "Por favor, llene este _________.",
answer: "formulario"},
{id: 5,
text: "¿Por favor, darse ________.",
answer: "vuelta"},
{id: 6,
text: "Voy a tomar su ________ ahora.",
answer: "temperatura"},
{id: 7,
text: "Por favor, siéntese aquí ________ esperamos al médico.",
answer: "mientras"},
{id: 8,
text: "¿Ha ________ alguna enfermedad  reciente?",
answer: "tenido"},
{id: 9,
text: "¿Cuándo fue su última ________ al médico?",
answer: "visita"},
{id: 10,
text: "Voy a medir su presión ________ ahora.",
answer: "arterial"},
{id: 11,
text: "¿Tiene algún problema de ________?",
answer: "alergia"},
{id: 12,
text: "¿Está tomando algún ________ en este momento?",
answer: "medicamento"},
{id: 13,
text: "¿Tiene alguna ________ o preocupación?",
answer: "pregunta"},
{id: 14,
text: "Por favor, muévase hacia la ________/izquierda.",
answer: "derecha"},
{id: 15,
text: "Voy a tomarle el ________.",
answer: "pulso"},
{id: 16,
text: "Por favor, muévase hacia la derecha/________.",
answer: "izquierda"},
{id: 17,
text: "Por favor, siga estas ________.",
answer: "instrucciones"},
{id: 18,
text: "¿Cómo ha sido su ________ recientemente?",
answer: "salud"},
{id: 19,
text: "¿Puede describir dónde está su ________?",
answer: "dolor"},
{id: 20,
text: "Muchas ________ por venir hoy.",
answer: "gracias"},
{id: 21,
text: "¿Por favor, acuéstese boca ________/abajo",
answer: "arriba"},
{id: 22,
text: "¿Por favor, acuéstese boca arriba/________",
answer: "abajo"},
]


export default phrases;
